### ISSUE TITLE
ADSync Profile Path

### ISSUE THREAD

**Issue by shadowprowler** [fox-it/adconnectdump#2]
Hi,
One issue I noticed in adconnectdump.py script is that on Windows Server 2019 (probably on 2016 as well), the ADSync profile path is under:  c:\Windows\ServiceProfiles\ADSync\AppData\Local\Microsoft\Credentials

On which OS version did you try the python script ?

thanks

**Comment by dirkjanm** [comment]
This was on server 2016, did you confirm changing the path fixed it for 2019? If so I can add it as additional search path, but don't have a 2019 box right now with ADSync

**Comment by dirkjanm** [comment]
Also I attempted to support multiple paths in https://github.com/fox-it/adconnectdump/commit/2d1a01bdee5d85ed0f959e5c51aa46c87f216aa5, if you can try it with that version and let me know if it works, that'd be much appreciated.

**Comment by shadowprowler** [comment]
> This was on server 2016, did you confirm changing the path fixed it for 2019? If so I can add it as additional search path, but don't have a 2019 box right now with ADSync

yes - i confirm, this is why I raised this issue



> Also I attempted to support multiple paths in [2d1a01b](https://github.com/fox-it/adconnectdump/commit/2d1a01bdee5d85ed0f959e5c51aa46c87f216aa5), if you can try it with that version and let me know if it works, that'd be much appreciated.

it works nicely, thanks for adapting the code

**Comment by dirkjanm** [comment]
Ty for the report and for letting me know it's resolved! closing this one
